"""add rounds and hole scores

Revision ID: 375be821bd00
Revises: a72d991fd146
Create Date: 2026-01-06 17:34:41.539008

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '375be821bd00'
down_revision = 'a72d991fd146'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rounds_course_id'), 'rounds', ['course_id'], unique=False)
    op.create_table('hole_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('hole_number', sa.Integer(), nullable=False),
    sa.Column('strokes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'hole_number', name='uq_score_round_hole')
    )
    op.create_index(op.f('ix_hole_scores_round_id'), 'hole_scores', ['round_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hole_scores_round_id'), table_name='hole_scores')
    op.drop_table('hole_scores')
    op.drop_index(op.f('ix_rounds_course_id'), table_name='rounds')
    op.drop_table('rounds')
    # ### end Alembic commands ###
