"""add_gender_specific_tee_ratings

Revision ID: f25403bfe5c4
Revises: 3b2c3a1b9a2f
Create Date: 2026-01-22 10:10:29.579497

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'f25403bfe5c4'
down_revision = '3b2c3a1b9a2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_tees', sa.Column('course_rating_men', sa.Float(), nullable=True))
    op.add_column('course_tees', sa.Column('slope_rating_men', sa.Integer(), nullable=True))
    op.add_column('course_tees', sa.Column('course_rating_women', sa.Float(), nullable=True))
    op.add_column('course_tees', sa.Column('slope_rating_women', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_tees', 'slope_rating_women')
    op.drop_column('course_tees', 'course_rating_women')
    op.drop_column('course_tees', 'slope_rating_men')
    op.drop_column('course_tees', 'course_rating_men')
    # ### end Alembic commands ###
