"""add user ownership

Revision ID: f5400019e0fb
Revises: 375be821bd00
Create Date: 2026-01-06 18:20:24.710721

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'f5400019e0fb'
down_revision = '375be821bd00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite can't add a NOT NULL column without a default, so we keep a temporary default.
    op.add_column(
        'courses',
        sa.Column('user_id', sa.String(length=128), nullable=False, server_default='dev-user'),
    )
    op.create_index(op.f('ix_courses_user_id'), 'courses', ['user_id'], unique=False)
    op.add_column(
        'rounds',
        sa.Column('user_id', sa.String(length=128), nullable=False, server_default='dev-user'),
    )
    op.create_index(op.f('ix_rounds_user_id'), 'rounds', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rounds_user_id'), table_name='rounds')
    op.drop_column('rounds', 'user_id')
    op.drop_index(op.f('ix_courses_user_id'), table_name='courses')
    op.drop_column('courses', 'user_id')
    # ### end Alembic commands ###
